FROM ubuntu:22.04

LABEL maintainer="zheyuma97@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=defaultuser
ARG UID=1000
ARG GID=1000

RUN apt update && apt upgrade -y && apt install -y \
    build-essential curl wget git vim ca-certificates sudo fish bear flex bison debootstrap \
    libslirp-dev cmake ninja-build pkg-config libvncserver-dev cpulimit libattr1-dev \
    libcap-ng-dev gcc-multilib libglib2.0-dev libpixman-1-dev autoconf libelf-dev libssl-dev \
    autopoint libfreetype-dev xorriso libvirglrenderer-dev libopengl-dev libepoxy-dev zip \
    python3-pip libbsd-dev libasound2-dev libabsl-dev tini bc python3-dev automake python3-setuptools \
	cargo libgtk-3-dev fd-find

RUN pip3 install python-ptrace psutil schedule pandas matplotlib gitpython pyyaml tomli sphinx sphinx_rtd_theme

RUN groupadd -g $GID $USERNAME && \
    useradd -u $UID -g $GID -ms /usr/bin/fish $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/$USERNAME

USER $USERNAME

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["fish"]
